version: '3.3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    volumes:
       - db_data:/var/lib/mysql

    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: reallysecure1
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  db_data: